import React, { useEffect, useState } from 'react';
import { IconArrowRight, IconCheck, IconFileText, IconMicrophone, IconPlayerPause, IconPlayerPlay, IconRefresh, IconTarget, IconMessageCircle, IconChartBar } from '@tabler/icons-react';
import './design-preview.css';

const stages=['Prepare','Begin','Go deeper','Reflect'];
export default function DesignPreview(){
 const params=new URLSearchParams(window.location.search),embed=params.has('embed');
 const [stage,setStage]=useState(Math.min(3,Math.max(0,Number(params.get('stage'))||0)));
 const [role,setRole]=useState('Software Engineer Intern');
 const [ready,setReady]=useState(true),[playing,setPlaying]=useState(true),[replay,setReplay]=useState(0),[typed,setTyped]=useState('');
 const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
 useEffect(()=>{setTyped('');let n=0;const text=stage===2?'I built a reporting tool that turns a business question into a dashboard. The hardest part was making sure every number could be traced back to the source.':'';if(reduced){setTyped(text);return;}const timer=setInterval(()=>{n+=3;setTyped(text.slice(0,n));if(n>=text.length)clearInterval(timer);},35);return()=>clearInterval(timer)},[stage,replay,reduced]);
 return <div className={`ip-shell ${embed?'ip-embed':''}`}>
  {!embed&&<aside className="ip-sidebar"><strong>Interview Coach</strong><span>YOUR PRACTICE STUDIO</span><nav>{stages.map((s,i)=><button key={s} className={i===stage?'active':''} onClick={()=>setStage(i)}>{[<IconFileText key="a"/>,<IconMicrophone key="b"/>,<IconMessageCircle key="c"/>,<IconChartBar key="d"/>][i]}{s}</button>)}</nav><small>INTERACTIVE DESIGN PREVIEW<br/>No recording. No AI requests.</small></aside>}
  <main className="ip-main"><header className="ip-topbar"><span>Practice studio <b>/ {stages[stage]}</b></span><button onClick={()=>{setReplay(x=>x+1);setPlaying(true)}}><IconRefresh size={15}/> Replay</button></header>
  <div className="ip-content" key={`${stage}-${replay}`}>
   <div className="ip-heading"><span>YOUR NEXT ROLE STARTS HERE · DEMO</span><h1>{['Good preparation. Real confidence.','Take a breath. Find your voice.','Go beyond the rehearsed answer.','Know what to bring next time.'][stage]}</h1></div>
   {stage===0&&<div className="ip-prep"><section className="ip-material"><div className="ip-section-label"><IconFileText size={19}/> YOUR EXPERIENCE</div><h2>Start with your story.</h2><div className="ip-resume"><IconFileText size={40}/><strong>Sample_Resume.pdf</strong><span>Example candidate · Software engineering</span><button onClick={()=>setReady(v=>!v)}>{ready?<><IconCheck size={16}/> Resume connected</>:'Use sample resume'}</button></div><p>Bring the experience you want to talk about.<br/>This preview uses sample information only.</p></section><section className="ip-role"><div className="ip-section-label"><IconTarget size={19}/> YOUR NEXT OPPORTUNITY</div><h2>Make practice personal.</h2><label htmlFor="role">Target role</label><input id="role" value={role} onChange={e=>setRole(e.target.value)}/><label htmlFor="job">What the role involves</label><textarea id="job" defaultValue="Build useful products, solve ambiguous problems, and collaborate with a team. Talk through your decisions and their impact."/><div className="ip-session"><span>Behavioral practice</span><span>30 minutes</span></div><button className="ip-primary" disabled={!ready||!role.trim()} onClick={()=>setStage(1)}>Start sample interview <IconArrowRight size={18}/></button></section></div>}
   {stage===1&&<section className="ip-first"><span className="ip-badge">QUESTION 01 · YOUR EXPERIENCE</span><h2>Tell me about a project you built.<br/><em>What challenge did you work through?</em></h2><div className="ip-breathe"><IconMicrophone size={28}/><span>Think about the problem, your decision, and the result.</span></div><button className="ip-primary" onClick={()=>setStage(2)}>Show a sample conversation <IconArrowRight size={19}/></button><small>No microphone or camera is activated in this preview.</small></section>}
   {stage===2&&<div className="ip-conversation"><section className="ip-dialogue"><span className="ip-section-label">YOUR ANSWER · SAMPLE TRANSCRIPT</span><p className="ip-transcript">{typed}<span className="ip-caret"/></p><div className="ip-followup"><span><IconMessageCircle size={18}/> A FOLLOW-UP THAT LISTENS</span><h2>How did you make sure the numbers were trustworthy?</h2><p>Walk me through one decision you made.</p></div><button className="ip-primary" onClick={()=>setStage(3)}>Finish & review <IconArrowRight size={17}/></button></section><section className="ip-voice"><span className="ip-badge">VOICE PRACTICE</span><div className={`ip-wave ${playing?'':'paused'}`} aria-hidden="true">{Array.from({length:25},(_,i)=><i key={i} style={{height:`${18+Math.sin(i*.7)**2*70}px`,animationDelay:`${i*-.12}s`}}/>)}</div><h2>{playing?'Your story, out loud.':'Take your time.'}</h2><p>Focus on the thinking behind your answer.</p><button onClick={()=>setPlaying(v=>!v)} aria-label={playing?'Pause sample animation':'Play sample animation'}>{playing?<IconPlayerPause size={20}/>:<IconPlayerPlay size={20}/>}</button><small>Illustrative voice activity · No audio recorded</small></section></div>}
   {stage===3&&<div className="ip-review"><section className="ip-score"><span className="ip-section-label">PRACTICE COMPLETE</span><strong>84<span>/100</span></strong><h2>A strong foundation.</h2><p>You explained your decisions clearly.<br/>Now make the impact just as concrete.</p><div className="ip-dimensions">{[['Clarity',88],['Structure',82],['Specificity',74]].map(([label,value])=><div key={label}><span>{label}<b>{value}</b></span><progress max="100" value={value}/></div>)}</div><small>Example feedback, not an assessment of you.</small></section><div className="ip-feedback"><section><span className="ip-section-label"><IconCheck size={18}/> KEEP DOING THIS</span><h2>You made your thinking visible.</h2><p>You connected the problem to a specific design decision, instead of only listing features.</p></section><section><span className="ip-section-label"><IconTarget size={18}/> TRY THIS NEXT</span><h2>Close with a concrete outcome.</h2><p>What changed because of your work? Add one real measure, user reaction, or lesson learned.</p><blockquote>“We checked the result against the source data before sharing the dashboard.”</blockquote></section><button className="ip-primary" onClick={()=>setStage(0)}>Practice again <IconArrowRight size={17}/></button></div></div>}
   {!embed&&<footer className="ip-footer"><span>Interactive UI concept · Sample scenario</span><button onClick={()=>setStage((stage+1)%4)}>Next: {stages[(stage+1)%4]} <IconArrowRight size={16}/></button></footer>}
  </div></main></div>
}
